// src/pages/creator/components/AIBuilderPreview.tsx

/**
 * @file AI Builder Preview — review interface for automatically generated labs.
 *
 * @remarks
 * This component displays a structured preview of a lab generated by the
 * **Altair AI-Builder**, allowing creators to review, edit, and approve
 * draft lab specifications before publishing.
 *
 * It is used in the Creator Dashboard flow after AI-assisted lab generation,
 * serving as a validation checkpoint where users can:
 * - Inspect each generated step and its metadata.
 * - Manually edit or correct content if needed.
 * - Approve the final draft for submission to the system.
 *
 * @packageDocumentation
 */
import DashboardCard from "@/components/ui/DashboardCard";


/**
 * Props for the {@link AIBuilderPreview} component.
 *
 * @property lab - The AI-generated lab object containing its metadata and step definitions.
 * @property onApprove - Triggered when the user confirms and approves the lab draft.
 * @property onBack - Triggered when the user returns to the previous step in the flow.
 * @property onManualEdit - Triggered when the user opts to manually edit the lab content.
 *
 * @public
 */
interface AIBuilderPreviewProps {
  lab: {
    title: string;
    environment: string;
    duration: string;
    level: string;
    steps: Array<{
      id: string;
      title: string;
      instruction: string;
      expected?: string;
    }>;
  };
  onApprove: () => void;
  onBack: () => void;
  onManualEdit: () => void; // ✅ new
}


/**
 * Displays a detailed preview of a lab generated by the Altair AI-Builder.
 *
 * @remarks
 * This component provides a clean, card-based interface summarizing metadata
 * and steps of the generated lab.  
 * It allows the creator to navigate back, manually edit, or approve the draft.
 *
 * @param lab - The generated lab object.
 * @param onApprove - Approve callback handler.
 * @param onBack - Back navigation handler.
 * @param onManualEdit - Manual edit handler.
 *
 * @returns React component rendering the AI-Builder lab preview.
 *
 * @public
 */
export default function AIBuilderPreview({
  lab,
  onApprove,
  onBack,
  onManualEdit,
}: AIBuilderPreviewProps) {
  return (
    <DashboardCard className="p-6 space-y-6">
      {/* HEADER */}
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h2 className="text-xl font-semibold text-white">{lab.title}</h2>
          <p className="text-sm text-gray-400 mt-1">
            {lab.level} • {lab.environment} • {lab.duration}
          </p>
          <p className="text-xs text-sky-400 mt-1 italic">
            Generated by AI-Builder
          </p>
        </div>

        <div className="flex gap-2">
          <button
            onClick={onBack}
            className="px-4 py-2 rounded-lg bg-[#1A1F2E] text-sm text-gray-200 hover:bg-[#23283a] transition"
          >
            Back
          </button>

          <button
            onClick={onManualEdit}
            className="px-4 py-2 rounded-lg bg-[#1A1F2E]/80 border border-purple-400/30 hover:bg-[#23283a] text-sm text-purple-300 hover:text-white transition"
          >
            Edit manually
          </button>

          <button
            onClick={onApprove}
            className="px-4 py-2 rounded-lg bg-gradient-to-r from-sky-400 to-purple-500 text-sm font-semibold hover:opacity-90 transition"
          >
            Approve this draft
          </button>
        </div>
      </div>

      {/* CONTENT */}
      <div className="space-y-4">
        {lab.steps.map((step, i) => (
          <div
            key={step.id}
            className="rounded-lg bg-[#0F1424]/70 border border-white/5 p-4"
          >
            <p className="text-xs text-gray-500 mb-1">Step {i + 1}</p>
            <h3 className="text-sm font-semibold text-white">{step.title}</h3>
            <p className="text-sm text-gray-300 mt-2">{step.instruction}</p>
            {step.expected && (
              <p className="text-xs text-gray-400 mt-2">
                Expected answer / command: <code>{step.expected}</code>
              </p>
            )}
          </div>
        ))}
      </div>
    </DashboardCard>
  );
}
